{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "9584e9e8-1eb7-4a8f-9b68-ccca8d1d1342",
   "metadata": {},
   "source": []
  },
  {
   "cell_type": "markdown",
   "id": "6337f02a-2732-4747-acdf-89323f2ec33f",
   "metadata": {},
   "source": [
    "# Reaction Wheel Inverted Pendulum \n",
    "\n",
    "## Overview\n",
    "\n",
    "The Reaction Wheel Inverted Pendulum is a complex system that combines a pendulum with a reaction wheel, this simulation implements Bang-bang controller to breing the pendulum up, then use LQR to keep it stable.\n",
    "\n",
    "### Features\n",
    "\n",
    "- **LQR Controller:** Stabilize the system using a Linear Quadratic Regulator (LQR) controller.\n",
    "\n",
    "- **PID Controller:** Stabilize the system by PID controller (Choose 1 Stabilize controller in ` param.py `).\n",
    "  \n",
    "- **Bang-Bang controller:** Implement a Bang-bang controller as a swing-up controller to bring the pendulum upright.\n",
    "\n",
    "- **Realistic Dynamics:** The simulation incorporates realistic dynamics and parameters of a DC motor and an inverted pendulum.\n",
    "\n",
    "## Getting Started\n",
    "\n",
    "### Prerequisites\n",
    "\n",
    "Ensure you have the following dependencies installed:\n",
    "\n",
    "- `numpy`\n",
    "- `pygame`\n",
    "- `matplotlib`\n",
    "- `PyQt5`\n",
    "- `pygetwindow`\n",
    "- `pyaudio`\n",
    "- `threading`\n",
    "- `control` (install via `pip install control`)\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "5ecf21cf",
   "metadata": {},
   "source": [
    "\n",
    "### Running the simulation\n",
    "\n",
    "## 1. Install Visual Studio Code (VS Code)\n",
    "\n",
    "Download it from:  \n",
    "https://code.visualstudio.com/\n",
    "\n",
    "## 2. Install Python\n",
    "\n",
    "Download and install from:  \n",
    "https://www.python.org/downloads/\n",
    "\n",
    "**Important:** During installation, make sure to enable the option \"Add Python to PATH\".\n",
    "\n",
    "## 3. Install Required Extensions in VS Code\n",
    "\n",
    "Open VS Code, click on the **Extensions** icon on the left sidebar, search for, and install:  \n",
    "- **Python** (by Microsoft)\n",
    "\n",
    "## 4. Download the GitHub Repository\n",
    "\n",
    "Access the repository here:  \n",
    "https://github.com/B-Paweekorn/Reaction-wheel-inverted-pendulum\n",
    "\n",
    "Then:  \n",
    "- Click the green **\"Code\"** button  \n",
    "- Select **\"Download ZIP\"**  \n",
    "- Extract the ZIP file (right-click > \"Extract here\" or \"Extract all\", depending on your OS)\n",
    "\n",
    "## 5. Open the Project Folder in VS Code\n",
    "\n",
    "Open VS Code and go to:  \n",
    "**File > Open Folder...**\n",
    "\n",
    "Select the folder you just extracted.\n",
    "\n",
    "## 6. Open the Terminal in VS Code\n",
    "\n",
    "Go to:  \n",
    "**Terminal > New Terminal**\n",
    "\n",
    "## 7. Install Project Dependencies\n",
    "\n",
    "In the terminal, type the following command (make sure you're in the correct folder):\n",
    "\n",
    "```bash\n",
    "pip install -r requirements.txt\n",
    "\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "0d931769",
   "metadata": {},
   "source": [
    " Clone the repository and install the dependencies:\n",
    "\n",
    "```bash\n",
    "git clone https://github.com/B-Paweekorn/Reaction-wheel-inverted-pendulum.git\n",
    "cd Reaction-wheel-inverted-pendulum\n",
    "pip install -r requirements.txt\n",
    "```\n",
    "\n",
    "<br>"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "43ceb8b7-b6ab-4589-9112-19ee5da194ca",
   "metadata": {},
   "source": [
    "## Usage\n",
    "\n",
    "![Image of the program](https://github.com/B-Paweekorn/Reaction-wheel-inverted-pendulum/assets/47713359/e2ff45d4-bfb2-4831-9ec9-334b88f8ff77)\n",
    "\n",
    "**Inject** - Type the amount of torque into the box and click `INJECT` or ENTER key to inject a disturbance to the system\n",
    "\n",
    "**Reset** - Click `RESET` to reset the system\n",
    "\n",
    "**Plotting** - Click on the pendulum plot or the plot window to plot the data\n",
    "\n",
    "Edit the parameters in ```param.py```\n",
    "\n",
    "<br>"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "20c7d7df-526b-4020-9bbf-62a9a99afa1d",
   "metadata": {},
   "source": [
    "## Methodology\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "### System Modeling\n",
    "\n",
    "The simulation involves modeling the dynamics of a Reaction Wheel Inverted Pendulum (RWIP) system. The key components include:\n",
    "\n",
    "\n",
    "\n",
    "***Reaction Wheel Inverted Pendulum Dynamics***\n",
    "\n",
    "<br>\n",
    "\n",
    "<img src=\"https://github.com/B-Paweekorn/Reaction-wheel-inverted-pendulum/assets/122732439/6c59b7a7-6aa7-4a73-b353-9e242e6aae1c\" width=\"480\">\n",
    "\n",
    "#### RWIP Parameter\n",
    "- `L1` - Pendulum length from orgin to center of mass\n",
    "- `L2` - Pendulum length\n",
    "- `m1` - Mass of pendulum\n",
    "- `m2` - Mass of fly wheel\n",
    "- `θp` - Angle of pendulum\n",
    "- `θr` - Angle of fly wheel\n",
    "- `I1` - Inertia moment of pendulum\n",
    "- `I2` - Inertia moment fly wheel and Innertia moment of motor\n",
    "- `g` - Gravitational acceleration\n",
    "- `Tm` - Torque apply by DC motor\n",
    "- `Td` - Disturbance"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "f1b8695e-66d0-4089-b378-c4f313a92141",
   "metadata": {},
   "source": [
    "#### Newton method\n",
    "\n",
    "tbd\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "09ae382f-2f18-4792-b45f-cef5c4abb481",
   "metadata": {},
   "source": [
    "#### Lagrange Method\n",
    "\n",
    "&emsp; $\\frac{d}{dt} \\left( \\frac{\\partial L}{\\partial \\dot{θ_r}} \\right) - \\frac{\\partial L}{\\partial θ_r} = 0$\n",
    "&emsp;&emsp; and\n",
    "\n",
    "&emsp; $\\frac{d}{dt} \\left( \\frac{\\partial L}{\\partial \\dot{θ_p}} \\right) - \\frac{\\partial L}{\\partial θ_p} = T_m$\n",
    "\n",
    "&emsp; Where Lagrangian (L) is\n",
    "\n",
    "&emsp; $L = K - V$\n",
    "\n",
    "\n",
    "#### Kinetic Energy\n",
    "\n",
    "&emsp; $K = \\frac{1}{2}(m_{1}L_{1}^{2}+m_{2}L_{2}^{2}+I_{1})\\dot{θ_p}^{2} + \\frac{1}{2}I_{2}(\\dot{θ_p}+\\dot{θ_r})^{2}$\n",
    "\n",
    "&emsp; $K = \\frac{1}{2}(m_{1}L_{1}^{2}+m_{2}L_{2}^{2}+I_{1}+I_{2})\\dot{θ_p}^{2} + I_{2}\\dot{θ_p}\\dot{θ_r} + \\frac{1}{2}I_{2}\\dot{θ_r}^{2}$\n",
    "\n",
    "#### Potential Energy\n",
    "\n",
    "&emsp; $V = (m_1L + m_2L)g\\cosθ_p$"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "a89fa513-8302-4546-83c2-5fd46a66b259",
   "metadata": {},
   "source": [
    "#### Mathematical equations of RWIP is described as\n",
    "\n",
    "&emsp; $\\ddot{\\theta_p} = \\frac{m_{1}gL_{1}\\sin\\left(\\theta_{p}\\right)\\ +\\ m_{2}gL_{2}\\sin\\left(\\theta_{p}\\right)\\ -\\ T_{m} +\\ T_{d}}{m_{1}L_{1}^{2}+m_{2}L_{2}+I_{1}}$\n",
    "\n",
    "<br>\n",
    "\n",
    "&emsp; $\\ddot{\\theta_r} = \\frac{T_{r}}{I_{2}}\\-\\frac{m_{1}gL_{1}\\ +\\ m_{2}gL_{2}\\ -\\ T_{m} +\\ T_{d}}{m_{1}L_{1}^{2}+m_{2}L_{2}+I_{1}}$\n",
    "\n",
    "<br>"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "8bff27b0-9fc4-4c44-82aa-46bc1f0c27c7",
   "metadata": {},
   "source": [
    "***DC Motor Dynamics***\n",
    "\n",
    "<img src=\"https://github.com/B-Paweekorn/Reaction-wheel-inverted-pendulum/assets/122732439/482f83f0-a4d7-4a70-b65e-006408f06a36\" width=\"480\">\n",
    "\n",
    "<br>\n",
    "\n",
    "#### Brushed DC Motor Parameter\n",
    "\n",
    "- `Vin` - Input Voltage\n",
    "- `R` - Motor resistance\n",
    "- `L` - Motor inductance\n",
    "- `i` - Motor current\n",
    "- `B` - Motor damped\n",
    "- `J` - Motor rotor Innertia\n",
    "- `ke` - Back EMF constant\n",
    "- `kt` - Torque constant\n",
    "\n",
    "#### Electrical part\n",
    "\n",
    "&emsp; $Vin = R i + L \\frac{di}{dt} + k_e θ_r$\n",
    "\n",
    "#### Mechanical Part\n",
    "\n",
    "&emsp; $T_{m} = Bθ_r + J\\frac{\\dot{θ_r}}{dt}$\n",
    "\n",
    "&emsp; $T_{m} = k_t i$\n",
    "<br>"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "fc345605-45f4-4f08-9e97-c978921d0868",
   "metadata": {},
   "source": [
    "### Controllers\n",
    "\n",
    "- **LQR Controller**: A linear quadratic regulator designed to stabilize the pendulum in the upright position.\n",
    "\n",
    "    \n",
    "    #### Linearization dynamics model ####\n",
    "  \n",
    "    - **Part RWIP**\n",
    " \n",
    "      when sinθp -> 0 sinθp = θp\n",
    "  \n",
    "    &emsp;&emsp;&emsp; $\\ddot{\\theta_p} = \\frac{m_{1}gL_{1}\\theta_{p}\\ +\\ m_{2}gL_{2}\\theta_{p}\\ -\\ T_{m} +\\ T_{d}}{m_{1}L_{1}^{2}+m_{2}L_{2}+I_{1}}$\n",
    "\n",
    "    &emsp;&emsp;&emsp; $\\ddot{\\theta_r} = \\frac{T_{m}}{I_{2}}\\-\\frac{m_{1}gL_{1}\\ +\\ m_{2}gL_{2}\\ -\\ T_{m} +\\ T_{d}}{m_{1}L_{1}^{2}+m_{2}L_{2}+I_{1}}$\n",
    "  \n",
    "    - **Part Motor**\n",
    "\n",
    "    &nbsp;&nbsp;&nbsp;We can estimate that L << R\n",
    "        \n",
    "    &emsp;&emsp;&emsp; $Vin = R i + k_e θ_r$\n",
    "\n",
    "    &emsp;&emsp;&emsp; $T_{m} = k_t i$\n",
    "\n",
    "    #### State space ####\n",
    "  \n",
    "  The proceeding equations are valid around the operating point where θp = 0\n",
    "  \n",
    "&emsp;&emsp;&emsp;&emsp;&emsp;\n",
    "![Matrix](https://latex.codecogs.com/svg.image?%5Cbegin%7Bbmatrix%7D%5Cdot%7B%5Ctheta_p%7D%5C%5C%5Cddot%7B%5Ctheta_p%7D%5C%5C%5Cdot%7B%5Ctheta_r%7D%5C%5C%5Cddot%7B%5Ctheta_r%7D%5Cend%7Bbmatrix%7D=%5Cbegin%7Bbmatrix%7D0&1&0&0%5C%5C%5Cfrac%7B(m_1L_1&plus;m_2L_2)g%7D%7Bm_1L_1%5E%7B2%7D&plus;m_2L_2%5E%7B2%7D&plus;J%7D&0&0&%5Cfrac%7Bk_tk_e%7D%7B(m_1L_1%5E%7B2%7D&plus;m_2L_2%5E%7B2%7D&plus;J)R%7D%5C%5C0&0&0&1%5C%5C-%5Cfrac%7B(m_1L_1&plus;m_2L_2)g%7D%7Bm_1L_1%5E%7B2%7D&plus;m_2L_2%5E%7B2%7D&plus;J%7D&0&0&-(%5Cfrac%7Bm_1L_1%5E%7B2%7D&plus;m_2L_2%5E%7B2%7D&plus;2J%7D%7B(m_1L_1%5E%7B2%7D&plus;m_2L_2%5E%7B2%7D&plus;J)J%7D)(%5Cfrac%7Bk_tk_e%7D%7BR%7D)%5C%5C%5Cend%7Bbmatrix%7D%5Cbegin%7Bbmatrix%7D%5Ctheta_p%5C%5C%5Cdot%7B%5Ctheta_p%7D%5C%5C%5Ctheta_r%5C%5C%5Cdot%7B%5Ctheta_r%7D%5Cend%7Bbmatrix%7D&plus;%5Cbegin%7Bbmatrix%7D0%5C%5C%5Cfrac%7Bk_t%7D%7B(m_1L_1%5E%7B2%7D&plus;m_2L_2%5E%7B2%7D&plus;J)R%7D%5C%5C0%5C%5C(%5Cfrac%7Bm_1L_1%5E%7B2%7D&plus;m_2L_2%5E%7B2%7D&plus;2J%7D%7B(m_1L_1%5E%7B2%7D&plus;m_2L_2%5E%7B2%7D&plus;J)J%7D)(%5Cfrac%7Bkt%7D%7BR%7D)%5Cend%7Bbmatrix%7DV_%7Bin%7D)\n",
    "\n",
    " - **PID Controller**:\n",
    "     The stabilize controller to compare with LQR\n",
    "    #### Transfer function ####\n",
    "   \n",
    "    &emsp;&emsp;&emsp; $\\Large\\frac{\\theta_{p}(s)}{\\tau_{m}(s)}=\\frac{\\frac{s}{-J-m_{2}L_{2}^{2}}}{s^{3}+\\left(\\frac{B}{I_{1}}+\\frac{B+d_{p}}{J+m_{2}L_{2}^{2}}\\right)s^{2}-\\left(\\frac{\\left(m_{1}L_{1}+m_{2}L_{2}\\right)g}{\\left(J+m_{2}L_{2}^{2}\\right)I_{1}}-\\frac{B\\cdot d_{p}}{\\left(J+m_{2}L_{2}^{2}\\right)I_{1}}\\right)s-\\frac{\\left(m_{1}L_{1}+m_{2}L_{2}\\right)Bg}{\\left(J+m_{2}L_{2}^{2}\\right)I_{1}}}$\n",
    "\n",
    "   #### Root Locus Design ####\n",
    "   \n",
    "     To predict the system's characteristics as the gain (Kp) is adjusted and poles move, design the root locus.\n",
    "      \n",
    "     &emsp;&emsp;&emsp; ![image](https://github.com/B-Paweekorn/Reaction-wheel-inverted-pendulum/assets/122732439/76fc37ed-f049-4606-9711-ea4dd4a56246)\n",
    "\n",
    "     Root Locus of the system by default parameter set. It has one zero (s = 0), and three poles (s = -74.93; s =-3.88e-3; s = 73.53).\n",
    "\n",
    "   #### Closed Loop Root Locus ####\n",
    "   \n",
    "   &emsp;&emsp;&emsp; ![image](https://github.com/B-Paweekorn/Reaction-wheel-inverted-pendulum/assets/122732439/31d1765a-d515-48da-8024-f94bcc96d6e3)\n",
    "   \n",
    "   &emsp; Where G(s) is Kp the gain can be adjusted ti make the closed loop poles to be in stable location The resultant Root Locus can be seen below (note to plot this graph in  `param.py` you need to set ` Stabilize_Controller ` to \"PID\" mode and set ` plot_rootlocus ` to \"True\") in this graph you can click pole position you want to know Gain `Kp` to adjust your system characteristics. \n",
    "   \n",
    "   &emsp;&emsp;&emsp;![image](https://github.com/B-Paweekorn/Reaction-wheel-inverted-pendulum/assets/122732439/692a1848-401b-4212-887d-eaeb9cc49548)\n",
    "\n",
    "- **Bang-bang Controller**: \n",
    "The swing up control routine and the stabilizing control routine are switched between -25 to 25 degree\n",
    "\n",
    "&nbsp;&nbsp; <img src=\"https://github.com/B-Paweekorn/Reaction-wheel-inverted-pendulum/assets/122732439/79e6d6d3-9ab2-49eb-a58b-3ad10a96a96b\" width=\"480\">\n",
    "\n",
    "- **Brake Controller**: Used as reduced energy of RWIP when RWIP have too much energy for stabilze\n",
    "### Sound Generation\n",
    "\n",
    "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; The simulation incorporates sound generation related to the speed of the reaction wheel. This feature adds an auditory element to the simulation, enhancing the user experience.\n",
    "\n",
    "<br>\n",
    "\n",
    "## Compare PID controller and LQR controller\n",
    "In this project, we explore and compare the performance of two different control strategies: PID (Proportional-Integral-Derivative) controller and LQR (Linear Quadratic Regulator) controller.\n",
    "<br>\n",
    "![image](https://github.com/B-Paweekorn/Reaction-wheel-inverted-pendulum/assets/122732439/714b7756-ad1f-469a-944b-afa281b2bc5b)\n",
    "\n",
    "***Linear quadratic regulator***\n",
    "<br>\n",
    "\n",
    "![CodeCogsEqn](https://github.com/B-Paweekorn/Reaction-wheel-inverted-pendulum/assets/122732439/8ce60949-f467-4ec1-8616-7e2be18518ba)\n",
    "| Error (deg)    | settling time (s) | Power (Watt) |\n",
    "| ---      | ---       | --- |\n",
    "| 5 |  0.66     | 0.6|\n",
    "| 6 |  0.73|     1.01   |\n",
    "| 7 |  0.85|1.75|\n",
    "| 8 |  1.07|        3.5|\n",
    "| 9 |  can't stabilize | can't stabilize |\n",
    "\n",
    "Max Disturbance : **9.32 Nm**\n",
    "\n",
    "***PID :*** Kp = 500 (choose form root locus)\n",
    "| Error (deg)    | settling time (s) | Power (Watt) |\n",
    "| ---      | ---       | --- |\n",
    "| 5 |  20.43| 10.06|\n",
    "| 6 |  21.02| 12.17 |\n",
    "| 7 |  21.37| 13.95 |\n",
    "| 8 |  21.59| 15.96 |\n",
    "| 9 |  can't stabilize | can't stabilize |\n",
    "\n",
    "Max Disturbance : **8.05 Nm**\n",
    "\n",
    "***PID :*** Kp = 215800 (choose form root locus)\n",
    "![image](https://github.com/B-Paweekorn/Reaction-wheel-inverted-pendulum/assets/122732439/2ecb7281-f6db-4a19-8914-fedf1de1eda6)\n",
    "***Notice*** that when choose unstable pole the system still stable because now it have **hardware limit** so the character of controller same like Fuzzy logic control to see unstable you need to unlock hardware limitation by set ` MotorLimit ` to **False** in ` param.py `\n",
    "\n",
    "### Conclusion\n",
    "\n",
    "|    | Stabilize boundary |\n",
    "| ---      | ---       | \n",
    "| **LQR** |  Can stabilize in every position  |\n",
    "| **PID** |  Can stabilize only in small boundary| \n",
    "\n",
    "**PID Controller**\n",
    "  The PID controller is a widely used feedback control system that relies on three components: Proportional, Integral, and Derivative. Here's a brief overview of each component:\n",
    "  \n",
    "  - Proportional (P): Reacts to the current error.\n",
    "  - Integral (I): Reacts to the accumulation of past errors.\n",
    "  - Derivative (D): Predicts future errors based on the rate of change.\n",
    "\n",
    "  **Advantages of PID:**\n",
    "  - Simplicity and ease of implementation.\n",
    "  - Effectiveness in a wide range of systems.\n",
    "  - Intuitive tuning parameters for performance optimization.\n",
    "  \n",
    "  **Considerations:**\n",
    "  - Tuning may be required for optimal performance in different systems.\n",
    "  - Limited capability to handle complex or nonlinear systems.\n",
    "<br>\n",
    "\n",
    "  **LQR Controller**\n",
    "  The LQR controller is designed based on the principles of optimal control theory. It minimizes a cost function that combines both state and control input, making it suitable for linear, time-invariant systems.\n",
    "\n",
    "**Advantages of LQR:**\n",
    "- Optimal control solution for linear systems.\n",
    "- Ability to handle systems with multiple inputs and outputs.\n",
    "- Incorporates a mathematical model for optimal performance.\n",
    "\n",
    "**Considerations:**\n",
    "- Requires a good understanding of the system dynamics for effective modeling.\n",
    "- Limited applicability to strictly linear systems.\n",
    "\n",
    "## Reference\n",
    "\n",
    "https://github.com/B-Paweekorn/Reaction-wheel-inverted-pendulum\n",
    "\n",
    "https://github.com/calcmogul/controls-engineering-in-frc \n",
    "\n",
    "- [Inverted Pendulum: State-Space Methods for Controller Design](https://ctms.engin.umich.edu/CTMS/index.php?example=InvertedPendulum&section=ControlStateSpace)\n",
    "\n",
    "- [Python 3D Printing Guide: Make STL Files From Masks] (https://www.youtube.com/watch?v=HNJduYogxh4)\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "918abcc5-e534-4f59-bb91-57529d887e99",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
