matrix:
- name: Python
  sources:
  - '**/*.py'
  aspell:
    lang: en
  dictionary:
    wordlists:
    - etc/codespell-ignore-words-list.txt
    output: wordlist.dic
    encoding: utf-8
  pipeline:
  - pyspelling.filters.python:
      comments: true
      docstrings: true
      group_comments: true
      decode_escapes: true
      strings: false
      string_types: fu
